baseurl = "/"
languageCode = "en-us"
title = "Ronverb Notes"
theme = "ghostwriter"

[Params]
    mainSections = ["post", "about"]
    intro = true
    headline = "Ronverbs 16:11"
    description = "Words (verbs) that may or may not matter"
    github = "https://github.com/rgeorgia"
    twitter = "https://twitter.com/RonGeorgia"
    email = "ronverbs@gmail.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"

[taxonomies]
    author = "authors"
    tag = "tags"
    category = "categories"
