#baseURL = "http://localhost:3000"
languageCode = "en-us"
license = "3-Clause BSD"
title = "Ronverbs 3:16"
theme = "ananke"
static = "static"
resources = "../resources"
images = "../images"
SectionPagesMenu = "main"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
ignoreLogs = [ "warning-goldmark-raw-html" ]

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

[languages]
[languages.en]
weight = 1
contentDir = "content"

[pagination]
pagerSize = 9

[params]
body_classes = "sans-serif bg-near-white"
post_content_classes = "bodoni"
background_color_class = "bg-black"
featured_image_class = "cover bg-top"
favicon = "../images/logo.jpg"
logo = "../images/logo.jpg"
logo_width = "200px"
recent_posts_number = 3
mainSections =  "life-group" 
cover_dimming_class = "bg-black-60"
read_more_copy = "Read more about this entry"
date_format = "date_full"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/rgeorgia"

[cascade]
featured_image = "/images/Christ-angels-deisis-2-GraceTruth.jpg"

[taxonomies]
tag = "tags"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
